version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.0.1-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - 16379:6379
    volumes:
      - cache:/var/lib/redis/data
    restart: always

volumes:
  db:
    driver: local
  cache: